### ISSUE TITLE
[us_9] Como usuario quiero poder asignar una foto de perfil

### ISSUE THREAD

**Issue by perezale** [Unicen-Tupar/transporte-solidario#26]

**Comment by gabi-cg** [comment]
Se terminan los cambios para la solución del issue.
En espera del OK de @perezale para solicitar el PR y mergear los cambios.

**Comment by perezale** [comment]
Espectacular!! anda 10 puntos!! Te jodo con lo último si llegás, sino mandalo como está.
El return del response->json debería ir dentro del bloque del archivo válido
file->()->isValid(){ 
...
 return ..;
}
y por fuera algo así (para poder enterarte en el frontend):
abort(403, 'Imagen no compatible, por favor utiliza formatos y tamaños de imagen compatibles.');

**Comment by gabi-cg** [comment]
ahh pectacular! claro dale, lo hago y mando el PR
