### ISSUE TITLE
[us_4] Como Admin quiero poder ver la lista de usuarios y validar como ONG algunos

### ISSUE THREAD

**Issue by jdottori** [Unicen-Tupar/transporte-solidario#4]

**Comment by VirutaMaster** [comment]
@jdottori, @perezale 

Con Facu estabamos mirando. Yo me confundí con las tareas asignadas en un excel anterior y empece a hacer este US_4 como si fuera la solicitud del US_5 (historial de viajes), que en realidad le toca a Facu.

Se le puede cambiar el numero a US_7 y comienzo los cambios correspondientes en una Branch con ese nombre? o preferis que deshaga todos los cambios a la version Base de US_4. Si la 2da opcion es la idonea, entonces te pido me indiques que macumbo hay que hacer para volver a la version Base el US_4.

Desde ya, muchas gracias.
Saludos!

**Comment by perezale** [comment]
Buenas! perdón la demora, estaba de viaje.

Si te parece más simple hace branch nuevo como us_7 para poder trabajar y vemos como sería la opción 2 en la semana con un ejemplo! saludoss
