### ISSUE TITLE
[us_6] Como usuario quiero poder registrame, cargando mi información de perfil

### ISSUE THREAD

**Issue by jdottori** [Unicen-Tupar/transporte-solidario#6]
La información de perfil incluye:
- Nombre
- Mail
- Facebook
- Webpage
- Texto descriptivo
- Número de teléfono
- (oculto) Campo de tipo de usuario

**Comment by gabi-cg** [comment]
Tener en cuenta que la información que se maneja en la tabla _users_ es:
- id
- nombre
- email
- clave
- facebook
- webpage
- descripcion
- telefono
- tipo_usuario
- fecha_alta
- img_path

**Comment by perezale** [comment]
Gabi, te pido cambiar el nombre de algunas columnas por si llega a haber
problemas con la herramienta para manejar el login (parte la vamos a reusar
de Lumen, tratemos de hacerlo lo mas straightforward posible)

nombre -> name
clave -> password

Saludos!

**Comment by gabi-cg** [comment]
Dale, para el mediodía lo subo.
Saludos.

**Comment by gabi-cg** [comment]
Re-abro el issue. Me encargo de crear la página de registro de usuario

**Comment by gabi-cg** [comment]
Me desasigno el issue ya que estaré ausente, si para cuando regrese sigue sin estar resuelto, me lo re-asigno.

**Comment by gabi-cg** [comment]
Creo la pantalla de registro de usuario, pero resultan varias dudas:

Archivo - función
- userController.php - setRegister
  no creo que los datos se consigan de esa manera
- user-controller.js - createUser
  No sé si está bien la llamada POST
- user-controller.js - loadRegister
  No se está cargando la funcionalidad del botón submit del formulario
- UserModel.php - setRegister
  No se están comprobando si las variables son nulas o si están seteadas.
  Debo realizar la función de convertir el password a Bcrypt antes de guardarlo

**Comment by perezale** [comment]
Se continua desarrollando a partir de 2017

**Comment by gabi-cg** [comment]
Agregamos función de encriptación de password window.btoa()

**Comment by gabi-cg** [comment]
Fixes para ingreso de email y pass, igualmente todos los inputs serán validados en issue  #32 .
Damos por terminado el issue.
