### ISSUE TITLE
[us_7] Como usuario quiero poder ver la información de perfil de cualquier usuario

### ISSUE THREAD

**Issue by jdottori** [Unicen-Tupar/transporte-solidario#7]
En los viajes y cualquier lugar donde aparezca un  nombre de usuario va a haber un link a la pagina de su perfil. Acá hay que hacer esa pagina de perfil del usuario. 
Ver #6 para los datos asociados.

**Comment by gabi-cg** [comment]
Armamos la vista mst para el perfil de los usuarios con sus datos.

**Comment by gabi-cg** [comment]
Saqué el handleNavigationEvents() que cada función del UserController.php llamaba.

**Comment by gabi-cg** [comment]
Es necesario agregar el control de que la opción Ver Perfil muestre la información del usuario logueado.
